# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Use three inputs to predict response using R.
#' @description Homework to deal with Rcpp
#' @param sigma the varients in normal distribution (numeric)
#' @param x0 the first number (numeric)
#' @param N the number you want to get (numeric)
#' @import microbenchmark
#' @importFrom Rcpp evalCpp
#' @importFrom stats rnorm rgamma
#' @useDynLib SC19088
#' @examples
#' \dontrun{
#' Metropolis(0.05,25,1000)
#' }
#' @export
metropolis <- function(sigma, x0, N) {
    .Call('_SC19088_metropolis', PACKAGE = 'SC19088', sigma, x0, N)
}

